<a href="https://colab.research.google.com/github/OscarDJB/CD_Databits/blob/main/Operaciones_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A continuación algunas de las funciones más utilizados en NumPy (siendo X un ndarray): - Suma: np.sum(X) - Raíz cuadrada: np.sqrt(X) - Promedio: np.mean(X) - Varianza: np.var(X) - Ordenamiento: np.sort(X) - Maximo, Minimo: np.max(X), np.min(X) - Indice de posición del valor Maximo: np.argmax(X) - Indice de posición del valor Minimo: np.argmin(X)

In [30]:
import numpy as np

x = np.array(list(range(100)))

#print(x)
np.random.seed(0)
y = np.random.randint(1,5,(100,1)) 
z = x + y

print(z)


print(np.mean(z[0:49]))
print(np.mean(z[51:]))

A = z[0:49]
B = z[51:]

print(A.shape)
print(B.shape)

C= np.concatenate((B,A), axis=0)
print(C.shape)
print(C)

C = C.reshape(1,9800)
print(C.shape)
print(C)

[[  1   2   3 ...  98  99 100]
 [  4   5   6 ... 101 102 103]
 [  2   3   4 ...  99 100 101]
 ...
 [  4   5   6 ... 101 102 103]
 [  2   3   4 ...  99 100 101]
 [  1   2   3 ...  98  99 100]]
52.11224489795919
52.05102040816327
(49, 100)
(49, 100)
(98, 100)
[[  2   3   4 ...  99 100 101]
 [  2   3   4 ...  99 100 101]
 [  2   3   4 ...  99 100 101]
 ...
 [  4   5   6 ... 101 102 103]
 [  4   5   6 ... 101 102 103]
 [  3   4   5 ... 100 101 102]]
(1, 9800)
